services:
  - type: web
    name: walwal
    runtime: node
    rootDir: front
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
